"""DemandOps API (Layer 7).

Serves the frozen pipeline artifacts (forecasts, risk scores, recommendations,
experiment metrics) and runs cheap what-if scenarios on request. Request
handlers never train models and never touch the database for analytical
endpoints — they consume the same CSV/JSON artifacts every other layer
produced, so API responses are exactly what the pipeline validated.

Interactive documentation is auto-generated by FastAPI at /docs (OpenAPI /
Swagger) — a primary artifact of this project, not a hidden one.
"""

from __future__ import annotations

from contextlib import asynccontextmanager
from pathlib import Path
from typing import Literal

import json

import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel, Field

from demandops import config
from demandops.simulator import apply_scenario

ARTIFACTS = {
    "forecasts": config.PROCESSED_DATA_DIR / "forecasts" / "gbm_holdout_predictions.csv",
    "risk": config.PROCESSED_DATA_DIR / "risk" / "risk_scores.csv",
    "recommendations": config.PROCESSED_DATA_DIR / "recommendations" / "recommendations.csv",
    "baseline_results": config.EXPERIMENTS_DIR / "baseline_results.json",
    "gbm_results": config.EXPERIMENTS_DIR / "gbm_results.json",
    "risk_summary": config.EXPERIMENTS_DIR / "risk_summary.json",
}

state: dict[str, object] = {}


def _load_artifact(name: str, path: Path) -> object | None:
    if not path.exists():
        return None
    if path.suffix == ".json":
        return json.loads(path.read_text(encoding="utf-8"))
    frame = pd.read_csv(path)
    if "date" in frame.columns:
        frame["date"] = pd.to_datetime(frame["date"])
    return frame


@asynccontextmanager
async def lifespan(app: FastAPI):
    for name, path in ARTIFACTS.items():
        state[name] = _load_artifact(name, path)
    yield
    state.clear()


app = FastAPI(
    title="DemandOps API",
    description=(
        "Quick-commerce demand & inventory decision platform. All analytical "
        "endpoints serve frozen, pipeline-validated artifacts; the /simulation "
        "endpoint applies cheap scenario arithmetic, never training."),
    version="0.1.0",
    lifespan=lifespan,
)


def _require(name: str) -> object:
    artifact = state.get(name)
    if artifact is None:
        raise HTTPException(
            status_code=503,
            detail=f"Artifact '{name}' is not available. Run the pipeline "
                   f"(expected at {ARTIFACTS[name].relative_to(config.PROJECT_ROOT)}).")
    return artifact


@app.get("/health")
def health() -> dict:
    """Liveness + artifact availability (503 never; status is reported)."""
    return {
        "status": "ok",
        "artifacts": {name: state.get(name) is not None for name in ARTIFACTS},
    }


@app.get("/forecast/summary")
def forecast_summary() -> dict:
    """Model evaluation metrics: baselines and the gradient-boosted model."""
    baselines = _require("baseline_results")
    gbm = _require("gbm_results")
    return {
        "baselines": {
            name: r["overall"]
            for name, r in baselines["results"].items()  # type: ignore[index]
        },
        "gbm": gbm["results"]["overall"],  # type: ignore[index]
        "gbm_model": gbm["model"],  # type: ignore[index]
        "split": baselines["split"],  # type: ignore[index]
    }


@app.get("/forecast/series/{unique_id}")
def forecast_series(unique_id: int,
                    limit: int = Query(28, ge=1, le=500)) -> list[dict]:
    """Daily forecast rows for one product-warehouse series."""
    forecasts: pd.DataFrame = _require("forecasts")  # type: ignore[assignment]
    rows = forecasts[forecasts["unique_id"] == unique_id]
    if rows.empty:
        raise HTTPException(status_code=404,
                            detail=f"Unknown series unique_id={unique_id}")
    rows = rows.sort_values("date").head(limit)
    rows = rows.copy()
    rows["date"] = rows["date"].dt.strftime("%Y-%m-%d")
    return rows.to_dict("records")


@app.get("/risk")
def risk(
    tier: Literal["HIGH", "MEDIUM", "LOW"] | None = None,
    limit: int = Query(50, ge=1, le=500),
) -> list[dict]:
    """Risk scores, optionally filtered by tier, highest unmet demand first."""
    risk_df: pd.DataFrame = _require("risk")  # type: ignore[assignment]
    rows = risk_df if tier is None else risk_df[risk_df["risk_tier"] == tier]
    rows = rows.sort_values(["estimated_unmet_units", "forecast_units"],
                            ascending=False).head(limit)
    # NaN -> null so the JSON is valid (JSON has no NaN).
    return rows.astype(object).where(pd.notna(rows), None).to_dict("records")


@app.get("/risk/summary")
def risk_summary() -> dict:
    return _require("risk_summary")


@app.get("/recommendations")
def recommendations(
    action: Literal["replenish_now", "replenish_scheduled",
                    "monitor", "investigate_data"] | None = None,
    limit: int = Query(50, ge=1, le=500),
) -> list[dict]:
    recs: pd.DataFrame = _require("recommendations")  # type: ignore[assignment]
    rows = recs if action is None else recs[recs["action"] == action]
    rows = rows.head(limit)
    return rows.to_dict("records")


class ScenarioParams(BaseModel):
    demand_multiplier: float = Field(1.0, ge=0)
    promotion_uplift: float = Field(0.0, ge=0)
    availability_improvement: float = Field(0.0, ge=0, le=1)


@app.post("/simulation")
def simulation(params: ScenarioParams) -> dict:
    """Cheap scenario arithmetic over the frozen risk table — no training."""
    risk_df: pd.DataFrame = _require("risk")  # type: ignore[assignment]
    try:
        scenario = apply_scenario(risk_df, params.demand_multiplier,
                                  params.promotion_uplift,
                                  params.availability_improvement)
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e)) from e
    top = scenario.nlargest(10, "unmet_units_delta")[
        ["unique_id", "name", "warehouse", "baseline_unmet_units",
         "scenario_unmet_units"]]
    top = top.astype(object).where(pd.notna(top), None)
    return {
        "scenario": params.model_dump(),
        "series": int(len(scenario)),
        "total_baseline_unmet_units": round(
            float(scenario["baseline_unmet_units"].sum()), 2),
        "total_scenario_unmet_units": round(
            float(scenario["scenario_unmet_units"].sum()), 2),
        "unmet_units_delta": round(float(scenario["unmet_units_delta"].sum()), 2),
        "total_scenario_recommended_units": int(
            scenario["scenario_recommended_units"].sum()),
        "top_increases": top.to_dict("records"),
    }
